---
- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: wxr-handler1-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address_2: 10.197.56.110

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: wxr-handler2-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address_2: 10.197.56.111

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: wxr-handler3-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address_2: 10.197.56.112
