---
- name: configure network
  hosts: 10.197.55.104
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address: 10.197.56.4
    - network_hostname: staging-receiver1-ub-16-04
    - network_interface: ens224
    - network_broadcast: 10.197.56.255
    - network_gateway: 10.197.56.254
    - network_network: 10.197.56.0

- name: configure network
  hosts: 10.197.55.105
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address: 10.197.56.5
    - network_hostname: staging-receiver2-ub-16-04
    - network_interface: ens224
    - network_broadcast: 10.197.56.255
    - network_gateway: 10.197.56.254
    - network_network: 10.197.56.0

- name: configure network
  hosts: 10.197.55.106
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address: 10.197.56.6
    - network_hostname: staging-receiver3-ub-16-04
    - network_interface: ens224
    - network_broadcast: 10.197.56.255
    - network_gateway: 10.197.56.254
    - network_network: 10.197.56.0
