module.exports = {
  "group": "system",
  "fields": [
    {
      "name": "sequenceNumber",
      "type": "unknown"
    }, {
      "name": "customerId",
      "type": "unknown"
    }, {
      "name": "dateTime",
      "type": "unknown"
    }, {
      "name": "timeOfDay",
      "type": "unknown"
    }, {
      "name": "computerName",
      "type": "unknown"
    }, {
      "name": "fdInterval",
      "type": "unknown"
    }, {
      "name": "processesTotal",
      "type": "unknown"
    }, {
      "name": "processesInteractive",
      "type": "unknown"
    }, {
      "name": "processesBatch",
      "type": "unknown"
    }, {
      "name": "processesNetwork",
      "type": "unknown"
    }, {
      "name": "processesDetached",
      "type": "unknown"
    }, {
      "name": "processesSubprocess",
      "type": "unknown"
    }, {
      "name": "computeQueueArchive",
      "type": "unknown"
    }, {
      "name": "cacheOverallAttempts",
      "type": "unknown"
    }, {
      "name": "cacheOverallAttempts",
      "type": "s"
    }, {
      "name": "cacheOverallHits",
      "type": "unknown"
    }, {
      "name": "cacheOverallHits",
      "type": "%"
    }, {
      "name": "acpMapcache",
      "type": "unknown"
    }, {
      "name": "cacheBitMapAttempts",
      "type": "unknown"
    }, {
      "name": "cacheBitMapAttempts",
      "type": "s"
    }, {
      "name": "cacheBitMapHits",
      "type": "unknown"
    }, {
      "name": "cacheBitMapHits",
      "type": "%"
    }, {
      "name": "acpDircache",
      "type": "unknown"
    }, {
      "name": "cacheDirDataAttempts",
      "type": "unknown"
    }, {
      "name": "cacheDirDataAttempts",
      "type": "s"
    }, {
      "name": "cacheDirDataHits",
      "type": "unknown"
    }, {
      "name": "cacheDirDataHits",
      "type": "%"
    }, {
      "name": "acpDindxcache",
      "type": "unknown"
    }, {
      "name": "acpSysacc",
      "type": "unknown"
    }, {
      "name": "cacheDirFcbAttempts",
      "type": "unknown"
    }, {
      "name": "cacheDirFcbAttempts",
      "type": "s"
    }, {
      "name": "cacheDirFcbHits",
      "type": "unknown"
    }, {
      "name": "cacheDirFcbHits",
      "type": "%"
    }, {
      "name": "acpHdrcache",
      "type": "unknown"
    }, {
      "name": "cacheHeaderAttempts",
      "type": "unknown"
    }, {
      "name": "cacheHeaderAttempts",
      "type": "s"
    }, {
      "name": "cacheHeaderHits",
      "type": "unknown"
    }, {
      "name": "cacheHeaderHits",
      "type": "%"
    }, {
      "name": "acpFidcache",
      "type": "unknown"
    }, {
      "name": "cacheIdAttempts",
      "type": "unknown"
    }, {
      "name": "cacheIdAttempts",
      "type": "s"
    }, {
      "name": "cacheIdHits",
      "type": "unknown"
    }, {
      "name": "cacheIdHits",
      "type": "%"
    }, {
      "name": "cpuBusy",
      "type": "%"
    }, {
      "name": "cpuMpSynch",
      "type": "%"
    }, {
      "name": "cpuInterrupt",
      "type": "%"
    }, {
      "name": "cpuKernel",
      "type": "%"
    }, {
      "name": "cpuExecutive",
      "type": "%"
    }, {
      "name": "cpuSupervisor",
      "type": "%"
    }, {
      "name": "cpuUser",
      "type": "%"
    }, {
      "name": "memoryPhysicalSize",
      "type": "unknown"
    }, {
      "name": "memoryUsed",
      "type": "%"
    }, {
      "name": "memoryFreeSize",
      "type": "unknown"
    }, {
      "name": "memoryModifiedSize",
      "type": "unknown"
    }, {
      "name": "memoryBadListSize",
      "type": "unknown"
    }, {
      "name": "memoryVmsPermSize",
      "type": "unknown"
    }, {
      "name": "memoryVmsWsSize",
      "type": "unknown"
    }, {
      "name": "vmsUserProcessWs",
      "type": "unknown"
    }, {
      "name": "vmsProcessWs",
      "type": "unknown"
    }, {
      "name": "userProcessWs",
      "type": "unknown"
    }, {
      "name": "nonpagedPool",
      "type": "unknown"
    }, {
      "name": "nonpagedPoolPages",
      "type": "unknown"
    }, {
      "name": "nonpagedPoolUsedPages",
      "type": "%"
    }, {
      "name": "nonpagedPoolLargest",
      "type": "unknown"
    }, {
      "name": "pagedPool",
      "type": "unknown"
    }, {
      "name": "pagedPoolPages",
      "type": "unknown"
    }, {
      "name": "pagedPoolUsedPages",
      "type": "%"
    }, {
      "name": "pagedPoolPages",
      "type": "%"
    }, {
      "name": "faultsTotal",
      "type": "unknown"
    }, {
      "name": "faultsTotal",
      "type": "s"
    }, {
      "name": "faultsSystem",
      "type": "s"
    }, {
      "name": "faultsHard",
      "type": "s"
    }, {
      "name": "faultsSystemHard",
      "type": "unknown"
    }, {
      "name": "fileSysFaults",
      "type": "s"
    }, {
      "name": "modifiedWrites",
      "type": "unknown"
    }, {
      "name": "modifiedWritePages",
      "type": "unknown"
    }, {
      "name": "swapsTotal",
      "type": "unknown"
    }, {
      "name": "swapFile",
      "type": "unknown"
    }, {
      "name": "swapFileUsed",
      "type": "unknown"
    }, {
      "name": "swapFileUsed",
      "type": "%"
    }, {
      "name": "pageFile",
      "type": "unknown"
    }, {
      "name": "pageFiles",
      "type": "kb"
    }, {
      "name": "pageFile%",
      "type": "%"
    }, {
      "name": "pageFileUsedMax",
      "type": "unknown"
    }, {
      "name": "globalPages",
      "type": "unknown"
    }, {
      "name": "globalPagesUsed",
      "type": "%"
    }, {
      "name": "globalSections",
      "type": "unknown"
    }, {
      "name": "globalSectionsUsed",
      "type": "%"
    }, {
      "name": "deadScans",
      "type": "unknown"
    }, {
      "name": "totalDiskIo",
      "type": "s"
    }, {
      "name": "devIoTotal",
      "type": "unknown"
    }, {
      "name": "fileSysIo",
      "type": "s"
    }, {
      "name": "fileSysReadIo",
      "type": "s"
    }, {
      "name": "fileSysWriteIo",
      "type": "s"
    }, {
      "name": "ioBuffered",
      "type": "unknown"
    }, {
      "name": "ioBuffered",
      "type": "s"
    }, {
      "name": "ioDirect",
      "type": "unknown"
    }, {
      "name": "ioDirect",
      "type": "s"
    }, {
      "name": "ioSplit",
      "type": "unknown"
    }, {
      "name": "ioSplit",
      "type": "s"
    }, {
      "name": "transfersWindowTurn",
      "type": "s"
    }, {
      "name": "mscpTotalOperations",
      "type": "unknown"
    }, {
      "name": "mscpTotalBlocks",
      "type": "unknown"
    }, {
      "name": "mscpBufferWaits",
      "type": "unknown"
    }, {
      "name": "fileSysCalls",
      "type": "unknown"
    }, {
      "name": "fileSysIo",
      "type": "unknown"
    }, {
      "name": "locksTotal",
      "type": "unknown"
    }, {
      "name": "locksRemote",
      "type": "unknown"
    }, {
      "name": "locksCount",
      "type": "int"
    }, {
      "name": "locksResourceCount",
      "type": "int"
    }, {
      "name": "decnetPkts",
      "type": "unknown"
    }, {
      "name": "decnetRoutingPkts",
      "type": "unknown"
    }, {
      "name": "decnetRoutingPktsLost",
      "type": "unknown"
    }, {
      "name": "decnetBufferFailures",
      "type": "unknown"
    }, {
      "name": "vccPages",
      "type": "unknown"
    }, {
      "name": "vccPagesUsed",
      "type": "unknown"
    }, {
      "name": "vccReadHits",
      "type": "unknown"
    }, {
      "name": "vccReadHits",
      "type": "%"
    }, {
      "name": "vccReadIo",
      "type": "unknown"
    }, {
      "name": "vccWriteIo",
      "type": "unknown"
    }
  ]
}
