---
# Install required packages

- name: install required packages
  apt: pkg=rabbitmq-server
       state=present
       force=yes
       allow_unauthenticated=yes

- name: Enable RabbitMQ plugins
  rabbitmq_plugin: names=rabbitmq_management
                   state=enabled

- name: install ssl-cert
  apt: pkg=ssl-cert state=present
  when: rabbitmq_ssl and rabbitmq_ssl_use_snakeoil_cert

- name: add rabbitmq user to the ssl-cert group
  user: name=rabbitmq append=yes groups=ssl-cert
  when: rabbitmq_ssl and rabbitmq_ssl_use_snakeoil_cert
