---
# RabbitMQ user and vhost management

- name: Remove guest acct
  command: rabbitmqctl delete_user guest
  when: (ansible_hostname == rabbitmq_cluster_master)

- name: Ensure the vhosts is present
  rabbitmq_vhost: name="{{ item }}"
  with_items: rabbitmq_vhosts
  ignore_errors: True
  tags: [configuration,rabbitmq]

- name: Add user
  command: rabbitmqctl add_user test test
  when: (ansible_hostname == rabbitmq_cluster_master)

- name: Set user tags.
  command: rabbitmqctl set_user_tags test administrator

- name: Set permissions
  command: rabbitmqctl set_permissions -p / test ".*" ".*" ".*"

- name: ensure the default vhost contains the HA policy
  rabbitmq_policy: name=HA pattern='{{ rabbitmq_ha_pattern }}'
  args:
   tags:
    "ha-mode": '{{ rabbitmq_ha_mode }}'
  when: rabbitmq_create_cluster and rabbitmq_ha_enabled

- name: Symlink RabbitMQ bin to sbin
  file: state=link src=/usr/lib/rabbitmq/bin dest=/usr/lib/rabbitmq/sbin
  tags: [configuration,rabbitmq]

- name: Enable the plugins
  command: rabbitmq-plugins enable rabbitmq_management
