---
- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: mxc-haproxy-active-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - network_address_1: 10.197.55.2

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: mxc-haproxy-passive-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - network_address_1: 10.197.55.3

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: mxc-haproxy-rmq-active-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - network_address_1: 10.197.55.32

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: mxc-haproxy-rmq-passive-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - network_address_1: 10.197.55.33
