---
- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: mxc-befe-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - vsphere_memory: 4092
    - network_address_1: 10.197.55.13
