---
- name: Install all npm dependencies
  apt: name={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=3600
  with_items:
    - build-essential
    - openssl
    - libssl-dev
    - pkg-config

- name: Add nodesource repository
  shell: curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -

- name: Install all nodejs dependencies
  apt: name=nodejs
       state=latest
       update_cache=yes
       cache_valid_time=3600

- name: add yarn key id
  apt_key:
    url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    state: present

- name: add yarn repository
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
  register: aptrepo

- name: update package cache
  apt:
    update_cache: yes
  when: aptrepo.changed

- name: install yarn
  apt:
    name: yarn
    state: latest
    update_cache: yes
    cache_valid_time: 3600