---
- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-worker1-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address: 10.197.55.107

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-worker2-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address: 10.197.55.108

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-worker3-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address: 10.197.55.109
