---
- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-haproxy-active-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address: 10.197.55.102

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-haproxy-passive-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address: 10.197.55.103

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-haproxy-rmq-active-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address: 10.197.55.132

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-haproxy-rmq-passive-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address: 10.197.55.133
