---
- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis-sentinel1-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - vsphere_memory: 8192
    - network_address: 10.197.55.123

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis-sentinel2-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - vsphere_memory: 8192
    - network_address: 10.197.55.124

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis-sentinel3-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - vsphere_memory: 8192
    - network_address: 10.197.55.125

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis1-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - vsphere_memory: 8192
    - network_address: 10.197.55.119

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis2-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - vsphere_memory: 8192
    - network_address: 10.197.55.120

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis3-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - vsphere_memory: 8192
    - network_address: 10.197.55.121

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis4-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - vsphere_memory: 8192
    - network_address: 10.197.55.122
