- name: configure network
  hosts: 10.197.55.110
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address: 10.197.57.10
    - network_hostname: staging-handler1-ub-16-04
    - network_interface: ens224
    - network_broadcast: 10.197.57.255
    - network_gateway: 10.197.57.254
    - network_network: 10.197.57.0

- name: configure network
  hosts: 10.197.55.111
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address: 10.197.57.11
    - network_hostname: staging-handler2-ub-16-04
    - network_interface: ens224
    - network_broadcast: 10.197.57.255
    - network_gateway: 10.197.57.254
    - network_network: 10.197.57.0

- name: configure network
  hosts: 10.197.55.112
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address: 10.197.57.12
    - network_hostname: staging-handler3-ub-16-04
    - network_interface: ens224
    - network_broadcast: 10.197.57.255
    - network_gateway: 10.197.57.254
    - network_network: 10.197.57.0
