---
- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: wxr-rethinkdb-master-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_full }}"
    - vsphere_memory: 8192
    - vsphere_cpu: 8
    - network_address_2: 10.197.56.126

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: wxr-rethinkdb-slave1-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_full }}"
    - vsphere_memory: 8192
    - vsphere_cpu: 8
    - network_address_2: 10.197.56.127

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: wxr-rethinkdb-slave2-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_full }}"
    - vsphere_memory: 8192
    - vsphere_cpu: 8
    - network_address_2: 10.197.56.128

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: wxr-rethinkdb-slave3-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_full }}"
    - vsphere_memory: 8192
    - vsphere_cpu: 8
    - network_address_2: 10.197.56.129

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: wxr-rethinkdb-slave4-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_full }}"
    - vsphere_memory: 8192
    - vsphere_cpu: 8
    - network_address_2: 10.197.56.130
