---
- name: Build and configure OpServe Infrastructure
  become: yes
  hosts: vagrant
  remote_user: ansible

  tasks:

# hosts file
- include: ../installation-playbooks/configure-hosts.yml
# installing
- include: ../installation-playbooks/install-rabbitmq.yml
- include: ../installation-playbooks/install-redis.yml
- include: ../installation-playbooks/install-rethinkdb.yml
- include: ../installation-playbooks/install-backend-frontend.yml
- include: ../installation-playbooks/configure-receivers.yml
- include: ../installation-playbooks/install-haproxy.yml
- include: ../installation-playbooks/install-haproxy-rmq.yml
- include: ../installation-playbooks/install-handler.yml
- include: ../installation-playbooks/configure-workers.yml
