---
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

- hosts: all
  become: yes
  vars:
    oracle_java_set_as_default: yes
  roles:
    - role: ../../../shared/ansible/common
    - role: ../../../shared/ansible/launchpad-ppa-webupd8
    - role: ../../../shared/ansible/oracle-java
    - role: ../../../shared/ansible/install-docker

- hosts: crowd
  become: yes
  vars:
    postgresql_password: postgres
    postgresql_user: postgres
    postgresql_db: postgres
    install_path: /opt/atlassian/crowd
    data_path: "/var/atlassian/application-data/crowd"
    http_port: 8095
    fqdn: crowd.appdev.bluechipdomain.co.uk
    crowd_user: crowd
    crowd_version: "2.11.0"
    nginx_config_items:
      - {name: "crowd", src: "nginx-crowd.j2"}
    certificate_items:
      - {src: "wildcard.appdev.bundle.crt", dest: "/etc/ssl/{{fqdn}}.crt"}
      - {src: "wildcard.appdev.key", dest: "/etc/ssl/{{fqdn}}.key"}
      - {src: "appdev.ca.cer", dest: "/etc/ssl/appdev.ca.cer"}
  roles:
    - role: ../../../shared/ansible/docker-postgres
    - role: ../../../shared/ansible/ssl-certificates
    - role: ./crowd
    - role: ../../../shared/ansible/nginx

- hosts: jira
  become: yes
  vars:
    postgresql_password: postgres
    postgresql_user: postgres
    postgresql_db: postgres
    install_path: "/opt/atlassian/jira"
    data_path: "/var/atlassian/application-data/jira"
    http_port: 8080
    fqdn: jira.appdev.bluechipdomain.co.uk
    nginx_config_items:
      - {name: "jira", src: "nginx-jira.j2"}
    certificate_items:
      - {src: "wildcard.appdev.bundle.crt", dest: "/etc/ssl/{{fqdn}}.crt"}
      - {src: "wildcard.appdev.key", dest: "/etc/ssl/{{fqdn}}.key"}
      - {src: "appdev.ca.cer", dest: "/etc/ssl/appdev.ca.cer"}
  roles:
    - role: ../../../shared/ansible/docker-postgres
    - role: ../../../shared/ansible/ssl-certificates
    - role: ./jira
    - role: ../../../shared/ansible/nginx

- hosts: bamboo
  become: yes
  vars:
    bamboo_version: "5.15.0.1"
    bamboo_user: bamboo
    postgresql_password: postgres
    postgresql_user: postgres
    postgresql_db: postgres
    install_path: "/opt/atlassian/bamboo"
    data_path: "/var/atlassian/application-data/bamboo"
    http_port: 8080
    fqdn: bamboo.appdev.bluechipdomain.co.uk
    nginx_config_items:
      - {name: "bamboo", src: "nginx-bamboo.j2"}
    certificate_items:
      - {src: "wildcard.appdev.bundle.crt", dest: "/etc/ssl/{{fqdn}}.crt"}
      - {src: "wildcard.appdev.key", dest: "/etc/ssl/{{fqdn}}.key"}
      - {src: "appdev.ca.cer", dest: "/etc/ssl/appdev.ca.cer"}  
  roles:
    - role: ../../../shared/ansible/docker-postgres
    - role: ../../../shared/ansible/ssl-certificates
    - role: ./bamboo
    - role: ../../../shared/ansible/nginx

- hosts: confluence
  become: yes
  vars:
    postgresql_password: postgres
    postgresql_user: postgres
    postgresql_db: postgres
    install_path: /opt/atlassian/confluence
    data_path: "/var/atlassian/application-data/jira"
    http_port: 8090
    synchrony_port: 8091
    nginx_config_items:
      - {name: "confluence", src: "nginx-confluence.j2"}
    fqdn: confluence.appdev.bluechipdomain.co.uk
    certificate_items:
      - {src: "wildcard.appdev.bundle.crt", dest: "/etc/ssl/{{fqdn}}.crt"}
      - {src: "wildcard.appdev.key", dest: "/etc/ssl/{{fqdn}}.key"}
      - {src: "appdev.ca.cer", dest: "/etc/ssl/appdev.ca.cer"}
  roles:
    - role: ../../../shared/ansible/docker-postgres
    - role: ../../../shared/ansible/ssl-certificates
    - role: ./confluence
    - role: ../../../shared/ansible/nginx