---
- name: Set hostname
  template: src=hostname.j2
            dest=/etc/hostname
            force=yes

- name: Configure hosts
  template: src=hosts.j2
            dest=/etc/hosts
            force=yes

- name: Configure interfaces
  template: src=interfaces.j2
            dest=/etc/network/interfaces
            force=yes

- name: restart machine
  shell: sleep 2 && shutdown -r now "Configuring network"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=0
  sudo: false
