---
- name: ensure parted is installed
  apt:
    name: parted
    state: latest
    cache_valid_time: 3600

- stat:
    path: /dev/sdb1
  register: partition

- name: create new partition
  command: "{{item}}"
  with_items:
  - parted -s /dev/sdb mklabel gpt
  - parted -s /dev/sdb unit mib mkpart primary 1 100%
  - parted -s /dev/sdb set 1 lvm on
  when: (not partition.stat.exists)

- name: extend lvm group and volume into new partition
  command: "{{item}}"
  with_items:
  - pvcreate /dev/sdb1
  - vgextend template-lvm-vg /dev/sdb1
  - lvextend -r /dev/template-lvm-vg/root /dev/sdb1
  when: (not partition.stat.exists)