---
- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: trn-handler1-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address: 10.197.56.10

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: trn-handler2-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address: 10.197.56.11

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: trn-handler3-ub-16-04
    - vsphere_template_name: "{{ vsphere_template_small }}"
    - network_address: 10.197.56.12
