---
- name: Modify hostname on loopback address on hosts file /etc/hosts
  lineinfile: dest=/etc/hosts
              regexp="^127.0.0.1.*"
              line='127.0.0.1       {{ ansible_nodename }}'

- name: Build hosts list
  lineinfile: dest=/etc/hosts
              regexp='.*{{ item }}$'
              line="{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_nodename }}"
              state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups[group_names[0]]
