---
- name: Check if Jira Exists
  stat:
    path: "{{install_path}}/uninstall"
  register: service_status

- name: Download jira binary.
  get_url:
    url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-7.3.1-x64.bin
    dest: /tmp/atlassian-jira-x64.bin
    checksum: sha256:8d9582e202642402508be71eb633de16af089fb93d25eba8cf9a6c85728a8db5
    mode: 0777
  when: (not service_status.stat.exists)

- name: Deploy varfile (install)
  template:
    src: install.varfile.j2
    dest: /tmp/response.varfile
    mode: 0777
  when: (not service_status.stat.exists)

- name: Execute installer
  shell: ./atlassian-jira-x64.bin -q -varfile response.varfile
  args:
    chdir: /tmp/
  when: (not service_status.stat.exists)

- name: Cleanup install files
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /tmp/response.varfile
    - /tmp/atlassian-jira-x64.bin

- name: Deploy config files.
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "server.xml.j2", dest: "{{install_path}}/conf/server.xml"}
  register: restartjira

- name: Deploy jdbc binary
  copy:
    src: files/postgresql-9.4.1212.jre6.jar
    dest: "{{install_path}}/lib/postgresql-9.1-903.jdbc4-atlassian-hosted.jar"
    mode: 0777
  register: reboot

- name: Use system jre
  lineinfile:
    dest: "{{install_path}}/bin/catalina.sh"
    state: absent
    regexp: '^JRE_HOME=/usr/bin/java'
    line: 'JRE_HOME=/usr/bin/java'
    insertafter: '#!/bin/sh'
  register: reboot

- name: Use system jre
  lineinfile:
    dest: "{{install_path}}/bin/catalina.sh"
    state: present
    regexp: '^JRE_HOME=/usr/lib/jvm/java-8-oracle/jre/'
    line: 'JRE_HOME=/usr/lib/jvm/java-8-oracle/jre/'
    insertafter: '#!/bin/sh'
  register: reboot

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot.changed

- name: waiting for server to respond
  local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 delay=10 timeout=300
  become: false
  when: reboot.changed

- name: Restart jira
  service:
    name: jira
    state: restarted
  when: restartjira.changed

- name: Ensure crowd service is started.
  service:
    name: jira
    state: started