---
- name: restart redis
  service:
    name: redis_{{ itheonx_redis_port }}
    state: restarted
  when: redis_as_service

- name: restart sentinel
  service:
    name: sentinel_{{ redis_sentinel_port }}
    state: restarted
  when: redis_as_service
