---
- name: Install docker and dependencies
  include: "os_family/{{ ansible_os_family }}.yml"

- name: Configure docker
  include: "configuration.yml"

- name: Blue chip extra tasks
  include: extra.yml