---
- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: mxc-receiver1-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address: 10.197.55.4
    - network_hostname: mxc-receiver1-ub-16-04

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: mxc-receiver2-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address: 10.197.55.5
    - network_hostname: mxc-receiver2-ub-16-04

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: mxc-receiver3-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address: 10.197.55.6
    - network_hostname: mxc-receiver3-ub-16-04
