---
- name: See RethinkDB group
  hosts: rethinkdb
  tasks: [ ]

- name: See be/fe
  hosts: be-fe
  tasks: [ ]

- name: See redis-sentinel group
  hosts: redis-sentinel
  tasks: [ ]

- name: Configure worker nodes and dependencies
  hosts: workers
  become: yes
  remote_user: ansible
  roles:
    - network-tuning
    - install-git
    - install-nodejs
    - install-recli
    - install-pm2
    - install-pm2-logrotate
    - deploy-certs
    - configure-workers
