---
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /usr/share/haproxy
haproxy_user: haproxy
haproxy_group: haproxy

# Frontend settings.
haproxy_frontend_name: 'hafrontend'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 80
haproxy_frontend_mode: 'http'

# Backend settings.
haproxy_backend_name: 'habackend'
haproxy_backend_mode: 'http'
haproxy_backend_balance_method: 'roundrobin'
haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'

# List of backend servers.
haproxy_backend_servers: []
  # - name: app1
  #   address: 192.168.0.1:80
  # - name: app2
  #   address: 192.168.0.2:80
haproxy_stats_port: 9443
haproxy_virtual_ip: # define IP in playbook
haproxy_receivers_port: 2919
itheonx_receivers_group: # define group in playbook
itheonx_dns: #define IP in playbook
itheonx_frontend_ip: 10.197.55.31
itheonx_backend_port: 8080
itheonx_socket_port: 5000
