---
- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis-sentinel1-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - vsphere_memory: 8192
    - vagrant_project: /opserve/staging-redis-sentinel1-ub-16-04
    - network_address_1: 10.197.55.123

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address_1: 10.197.55.123
    - network_hostname: staging-redis-sentinel1-ub-16-04

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis-sentinel2-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - vsphere_memory: 8192
    - vagrant_project: /opserve/staging-redis-sentinel2-ub-16-04
    - network_address_1: 10.197.55.124

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address_1: 10.197.55.124
    - network_hostname: staging-redis-sentinel2-ub-16-04

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis-sentinel3-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - vsphere_memory: 8192
    - vagrant_project: /opserve/staging-redis-sentinel3-ub-16-04
    - network_address_1: 10.197.55.125

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address_1: 10.197.55.125
    - network_hostname: staging-redis-sentinel3-ub-16-04

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis1-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - vsphere_memory: 8192
    - vagrant_project: /opserve/staging-redis1-ub-16-04
    - network_address_1: 10.197.55.119

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address_1: 10.197.55.119
    - network_hostname: staging-redis1-ub-16-04


- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis2-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - vsphere_memory: 8192
    - vagrant_project: /opserve/staging-redis2-ub-16-04
    - network_address_1: 10.197.55.120

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address_1: 10.197.55.120
    - network_hostname: staging-redis2-ub-16-04

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis3-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - vsphere_memory: 8192
    - vagrant_project: /opserve/staging-redis3-ub-16-04
    - network_address_1: 10.197.55.121

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address_1: 10.197.55.121
    - network_hostname: staging-redis3-ub-16-04

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-redis4-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - vsphere_memory: 8192
    - vagrant_project: /opserve/staging-redis4-ub-16-04
    - network_address_1: 10.197.55.122

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address_1: 10.197.55.122
    - network_hostname: staging-redis4-ub-16-04
