---
- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-handler1-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - vagrant_project: /etc/vagrant/staging-handler1-ub-16-04
    - network_address_1: 10.197.55.110

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address_1: 10.197.55.110
    - network_hostname: staging-handler1-ub-16-04

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-handler2-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - vagrant_project: /etc/vagrant/staging-handler2-ub-16-04
    - network_address_1: 10.197.55.111

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address_1: 10.197.55.111
    - network_hostname: staging-handler2-ub-16-04

- name: create vm
  hosts: vagrant
  become: yes
  remote_user: ansible
  roles:
    - create-vm
  vars:
    - vsphere_name: staging-handler3-ub-16-04
    - vsphere_template_name: /opserve/template-small-ub-16-04
    - vagrant_project: /etc/vagrant/staging-handler3-ub-16-04
    - network_address_1: 10.197.55.112

- name: configure network
  hosts: template
  become: yes
  remote_user: ansible
  roles:
    - configure-network
  vars:
    - network_address_1: 10.197.55.112
    - network_hostname: staging-handler3-ub-16-04
