---
- name: Make directory for ha.cf.j2 template
  file: path=/etc/ha.d
        mode=0644
        state=directory

- name: Deploy ha.cf.j2 template
  template:
    src: ha.cf.j2
    dest: "/etc/ha.d/ha.cf"
    mode: 0644
    force: yes

- name: restart heartbeat
  command: /etc/init.d/heartbeat restart

- name: start haproxy
  command: service haproxy start
